services:
  app:
    container_name: ruleslawyer-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  admin:
    container_name: ruleslawyer-admin
    build:
      context: ../frontends/board-game-admin
    ports:
      - 8081:80
    env_file:
      - ../frontends/board-game-admin/.env

  postgres:
    image: postgres:14.9
    container_name: ruleslawyer-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    name: ruleslawyer-db