services:
  app:
    container_name: ruleslawyer-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15.3
    container_name: ruleslawyer-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: ruleslawyer-db