name: Run Unit Tests before Merge

on:
  pull_request:
  merge_group:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM Install
        run: npm install --legacy-peer-deps

      - name: Unit Test
        run: npm run test
